Members only (secret_society)
ajkacca457/members_only pull request #1
Opened 2020-11-03 20:44 UTC by ajkacca457

Secret society application contains the following features :
- Sign up new members
- New member can create secret posts
- No one can see the author's name and post description until they sign up or sign in.
- Hide post authors when not logged in
- Log in or Logout
- Members can only edit or delete their own posts.

2020-11-03 21:23 UTC, rOluochKe requested changes
Hello @ajkacca457 
### You did well in this project :clap: However, you have a few issues to fix:-
- [ ] It creates the application routes using `resources :posts, only: [:new, :create, :index]`
- [ ] Repeated components in the views can be put in the helpers ie posts/index.html.erb
### Make the changes and submit for another code review. Good luck.
- Happy coding!

2020-11-04 05:01 UTC, ajkacca457 commented
@rOluochKe Thank you very much for your review. It was very helpful in case of improving my project. Based on your review I have updated the routes, got read of some unnecessary view files. I have also created a separate partial for repeated code so that index view file is not overcrowded. I hope that my changes will meet the requirements.

2020-11-04 05:14 UTC, maelfosso approved these changes
# Congratulations 👏🏾 

Thank you for implementing the suggested changes.
You can merge it now 👍🏾 

But before you do it, please, implement the changes from the comments left below.

Thanks and Good continuation 🤝 

Mael FOSSO

2020-11-04 05:14 UTC, maelfosso commented on app/views/posts/index.html.erb
> +<% end %>
Kindly remove logic from views, implement them into view helpers

2020-11-04 05:14 UTC, maelfosso commented on app/views/posts/_card.html.erb
> +  <% end %>
Kindly remove logic from views, implement them into view helpers

2020-11-04 05:30 UTC, merged